id: !!int 239
contentType: Card
title: Basic card with TestData
name: atm-pto-status
CollectionMode: '{"CollectionMode":"0"}'
MaxItems: '{"MaxItems":"3"}'
Priority: '{"Priority":"5"}'
StreamSource: null
CardComponent: template-video-card/template-video-card-card
CommonPart:
  Owner: !!int 2
  Container: null
  CreatedUtc: 2016-04-18T13:09:32.4032349Z
  PublishedUtc: 2017-01-22T13:22:36.3090924Z
  ModifiedUtc: 2017-01-22T13:22:35.8799588Z
  VersionCreatedUtc: 2017-01-22T13:22:35.0000000
  VersionPublishedUtc: 2017-01-22T13:22:36.0000000
  VersionModifiedUtc: 2017-01-22T13:22:35.0000000
ServicePart:
  ConnectorTypeId: !!int 0
  ConnectorName: Script
  ServiceName: Script
  Url: ~/api/adenin.GateKeeper.Script
  ServiceParameters: '{}'
SearchContextPart:
  Query: null
  Interface: null
CommandPart:
  CommandType: None
  Command: 
  DefaultDate: null
  Intent: null
AppPart:
  App: null
  Url: 
  ExtUrl: 
  Priority: !!int 0
  AppFaceId: !!int 0
  Category: orange
  Icon: now:search
  CSSClasses: null
  Enabled: !!bool false
  NewWindow: !!bool false
  UrlWithId: !!bool true
  AvailableAppFaceRecords: null
  HasPattern: !!bool false
RoleViewPermissionsPart:
  AllowedRoles:
    - Authenticated
  Audiences:
    - Administrator
  Mandatory: False
RecurringTaskPart:
  Schedule: '- - - - -'
  ActivityType: adenin.Now.Activities.CardTask.UpdateCard
  StartDateUtc: null
  EndDateUtc: null
  NextOccurrenceUtc: null
  Priority: !!int 5
  Status: Enabled
  NowFlag: 0
  LastExecutionUTC: null
  EnableWebHook: !!bool false
  WebHookToken: null
